Repository prgrms-web-devcourse/Team-Gaerval-Dadok-BE, pull requests merged in 2023-03, with the labels that each got.

#41 [#8 ][#12 ] 프로필 노출용 책장 요약 조회 구현, 책장 추천 쿼리 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfController.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/SummaryBookshelfResponse.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfRepository.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/BookshelfService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfService.java
  src/main/java/com/dadok/gaerval/domain/user/service/DefaultUserService.java
  src/main/java/com/dadok/gaerval/global/error/ErrorCode.java
  src/main/java/com/dadok/gaerval/global/error/handler/GlobalExceptionHandler.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfControllerIntegrationTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfRepositoryTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfServiceSliceTest.java
Labels: 백엔드, :sparkles: feat, :white_check_mark: test

#43 [#9]feat : 책검색 API 구현
  build.gradle
  src/main/java/com/dadok/gaerval/domain/book/api/BookController.java
  src/main/java/com/dadok/gaerval/domain/book/converter/BookMapper.java
  src/main/java/com/dadok/gaerval/domain/book/dto/request/SearchTarget.java
  src/main/java/com/dadok/gaerval/domain/book/dto/request/SortingPolicy.java
  src/main/java/com/dadok/gaerval/domain/book/dto/response/BookResponses.java
  src/main/java/com/dadok/gaerval/domain/book/dto/response/OriginalBookData.java
  src/main/java/com/dadok/gaerval/domain/book/dto/response/SearchBookResponse.java
  src/main/java/com/dadok/gaerval/domain/book/entity/Book.java
  src/main/java/com/dadok/gaerval/domain/book/exception/InvalidBookDataException.java
  src/main/java/com/dadok/gaerval/domain/book/repository/BookRepository.java
  src/main/java/com/dadok/gaerval/domain/book/service/BookService.java
  src/main/java/com/dadok/gaerval/domain/book/service/DefaultBookService.java
  src/main/java/com/dadok/gaerval/global/config/webclient/WebClientConfig.java
  src/main/java/com/dadok/gaerval/global/config/webclient/WebClientProperties.java
  src/main/java/com/dadok/gaerval/global/error/ErrorCode.java
  src/main/resources/application-api.yml
  src/main/resources/application.yml
  src/test/java/com/dadok/gaerval/domain/book/entity/BookTest.java
  src/test/java/com/dadok/gaerval/testutil/BookObjectProvider.java
Labels: 백엔드, :sparkles: feat

#44 [#12 ] bookshelfService에서 UserService 제외
  src/main/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfController.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfRepository.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/BookshelfService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfService.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfRepositoryTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfServiceSliceTest.java
Labels: 백엔드, :white_check_mark: test, :bug: fix

#45 [#5 ] 유저 회원가입시 책장도 생성하도록 수정
  src/main/java/com/dadok/gaerval/domain/user/service/DefaultUserService.java
  src/test/java/com/dadok/gaerval/domain/user/service/DefaultUserServiceSliceTest.java
Labels: :sparkles: feat, :recycle: refactor

#46 [#10 ] insertBookItem test 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/book/dto/request/BookCreateRequest.java
  src/main/java/com/dadok/gaerval/domain/user/api/UserController.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfServiceSliceTest.java
Labels: :white_check_mark: test

#47 [#9]test : 책검색 API Slice 테스트 구현
  src/docs/asciidoc/index.adoc
  src/test/java/com/dadok/gaerval/domain/book/api/BookControllerSliceTest.java
  src/test/java/com/dadok/gaerval/testutil/BookObjectProvider.java
Labels: :white_check_mark: test

#51 [chore] docs 필드 테이블 추가, jobGroup 링크 연결
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/job/entity/JobGroup.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfControllerSliceTest.java
Labels: :memo: chore

#52 feat : 책장 정보 조회 api 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfController.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/BookShelfDetailResponse.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfRepository.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfSupport.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/BookshelfService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfService.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfRepositoryTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfServiceSliceTest.java
Labels: :sparkles: feat

#54 findUserProfile api 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/user/api/UserController.java
  src/main/java/com/dadok/gaerval/domain/user/dto/response/UserProfileResponse.java
  src/main/java/com/dadok/gaerval/domain/user/repository/UserSupport.java
  src/main/java/com/dadok/gaerval/domain/user/repository/UserSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/user/service/DefaultUserService.java
  src/test/java/com/dadok/gaerval/domain/user/api/UserControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/dadok/gaerval/domain/user/service/DefaultUserServiceSliceTest.java
Labels: 백엔드, :sparkles: feat, :white_check_mark: test

#56 Feature/user refactor
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/request/BooksInBookShelfFindRequest.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/entity/Bookshelf.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookShelfItemSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/user/api/UserController.java
  src/main/java/com/dadok/gaerval/domain/user/dto/request/UserChangeProfileRequest.java
  src/main/java/com/dadok/gaerval/domain/user/dto/response/UserDetailResponse.java
  src/main/java/com/dadok/gaerval/domain/user/dto/response/UserNicknameExistsResponse.java
  src/main/java/com/dadok/gaerval/domain/user/entity/User.java
  src/main/java/com/dadok/gaerval/domain/user/exception/DuplicateNicknameException.java
  src/main/java/com/dadok/gaerval/domain/user/repository/UserRepository.java
  src/main/java/com/dadok/gaerval/domain/user/repository/UserSupport.java
  src/main/java/com/dadok/gaerval/domain/user/repository/UserSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/user/service/DefaultUserService.java
  src/main/java/com/dadok/gaerval/domain/user/service/UserService.java
  src/main/java/com/dadok/gaerval/domain/user/vo/Nickname.java
  src/main/java/com/dadok/gaerval/global/error/ErrorCode.java
  src/main/java/com/dadok/gaerval/global/error/exception/BusinessException.java
  src/main/java/com/dadok/gaerval/global/error/exception/DuplicateException.java
  src/main/java/com/dadok/gaerval/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/dadok/gaerval/global/error/response/ErrorResponse.java
  src/main/java/com/dadok/gaerval/global/util/RegexHelper.java
  src/test/java/com/dadok/gaerval/controller/ControllerTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/repository/BookShelfItemSupportImplTest.java
  src/test/java/com/dadok/gaerval/domain/user/api/UserControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/user/entity/UserTest.java
  src/test/java/com/dadok/gaerval/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/dadok/gaerval/domain/user/service/DefaultUserServiceSliceTest.java
  src/test/java/com/dadok/gaerval/testutil/WithMockCustomOAuth2LoginUser.java
  src/test/java/com/dadok/gaerval/testutil/WithMockCustomOAuth2LoginUserSecurityContextFactory.java
Labels: :sparkles: feat, :recycle: refactor, :white_check_mark: test

#55 [#34] feat : 도서 상세정보조회 API 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/book/api/BookController.java
  src/main/java/com/dadok/gaerval/domain/book/converter/BookMapper.java
  src/main/java/com/dadok/gaerval/domain/book/dto/response/BookResponse.java
  src/main/java/com/dadok/gaerval/domain/book/entity/Book.java
  src/main/java/com/dadok/gaerval/domain/book/repository/BookRepository.java
  src/main/java/com/dadok/gaerval/domain/book/service/BookService.java
  src/main/java/com/dadok/gaerval/domain/book/service/DefaultBookService.java
  src/test/java/com/dadok/gaerval/domain/book/api/BookControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book/repository/BookRepositoryTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/DefaultBookServiceTest.java
  src/test/java/com/dadok/gaerval/testutil/BookObjectProvider.java
Labels: 백엔드, :sparkles: feat

#61 feat : 슬랙 모듈 구현
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/dadok/gaerval/DadokApplication.java
  src/main/java/com/dadok/gaerval/domain/user/entity/User.java
  src/main/java/com/dadok/gaerval/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/dadok/gaerval/infra/slack/SlackException.java
  src/main/java/com/dadok/gaerval/infra/slack/SlackMessage.java
  src/main/java/com/dadok/gaerval/infra/slack/SlackService.java
  src/main/resources/application.yml
  src/test/java/com/dadok/gaerval/controller/ControllerTest.java
  src/test/java/com/dadok/gaerval/oauth/Oauth2Test.java
Labels: :sparkles: feat

#62 [#60] Web Client 추상화, 수신 데이터 전처리
  src/main/java/com/dadok/gaerval/domain/book/entity/Book.java
  src/main/java/com/dadok/gaerval/domain/book/service/BookDataProcessor.java
  src/main/java/com/dadok/gaerval/domain/book/service/DefaultBookService.java
  src/main/java/com/dadok/gaerval/global/config/externalapi/ExternalBookApiOperations.java
  src/main/java/com/dadok/gaerval/global/config/externalapi/WebClientBookApiOperations.java
  src/main/java/com/dadok/gaerval/global/config/externalapi/WebClientConfig.java
  src/main/java/com/dadok/gaerval/global/config/externalapi/WebClientProperties.java
  src/main/java/com/dadok/gaerval/global/util/CommonValidator.java
  src/test/java/com/dadok/gaerval/domain/book/entity/BookTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/BookDataProcessorTest.java
Labels: 백엔드, :sparkles: feat

#63 bookgroup entity 추가
  src/main/java/com/dadok/gaerval/domain/bookGroup/entity/BookGroup.java
  src/main/java/com/dadok/gaerval/domain/bookGroup/entity/GroupMember.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfItemRepository.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfRepository.java
  src/test/java/com/dadok/gaerval/domain/bookGroup/entity/BookGroupTest.java
  src/test/java/com/dadok/gaerval/domain/bookGroup/entity/GroupMemberTest.java
  src/test/java/com/dadok/gaerval/testutil/BookGroupObjectProvider.java
Labels: 백엔드, :sparkles: feat, :white_check_mark: test

#64 Feature/book suggestions - 직군별 책 추천 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/book/api/BookController.java
  src/main/java/com/dadok/gaerval/domain/book/dto/request/SuggestionsBookFindRequest.java
  src/main/java/com/dadok/gaerval/domain/book/dto/response/SuggestionsBookFindResponse.java
  src/main/java/com/dadok/gaerval/domain/book/dto/response/SuggestionsBookFindResponses.java
  src/main/java/com/dadok/gaerval/domain/book/repository/BookRepository.java
  src/main/java/com/dadok/gaerval/domain/book/repository/BookSupport.java
  src/main/java/com/dadok/gaerval/domain/book/repository/BookSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/book/service/BookService.java
  src/main/java/com/dadok/gaerval/domain/book/service/DefaultBookService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/BookInShelfResponses.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/entity/Bookshelf.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/entity/BookshelfItem.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookShelfItemSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/user/entity/User.java
  src/main/java/com/dadok/gaerval/domain/user/repository/UserSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/user/service/DefaultUserService.java
  src/main/java/com/dadok/gaerval/global/common/EnumType.java
  src/main/java/com/dadok/gaerval/global/common/JacocoExcludeGenerated.java
  src/main/java/com/dadok/gaerval/global/error/exception/InvalidArgumentException.java
  src/main/java/com/dadok/gaerval/global/error/handler/GlobalExceptionHandler.java
  src/test/java/com/dadok/gaerval/domain/book/api/BookControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book/repository/BookRepositoryTest.java
  src/test/java/com/dadok/gaerval/domain/book/repository/BookSupportImplTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/DefaultBookServiceSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/DefaultBookServiceTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/entity/BookshelfItemTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/entity/BookshelfItemTypeTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/entity/BookshelfTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/repository/BookShelfItemSupportImplTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfItemRepositoryTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfServiceSliceTest.java
  src/test/java/com/dadok/gaerval/domain/user/entity/UserTest.java
  src/test/java/com/dadok/gaerval/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/dadok/gaerval/domain/user/service/DefaultUserServiceSliceTest.java
  src/test/java/com/dadok/gaerval/testutil/UserObjectProvider.java
Labels: :sparkles: feat, :recycle: refactor, :white_check_mark: test

#65 유저 이름 변경 api 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/user/api/UserController.java
  src/main/java/com/dadok/gaerval/domain/user/dto/request/NicknameChangeRequest.java
  src/main/java/com/dadok/gaerval/domain/user/exception/DuplicateNicknameException.java
  src/main/java/com/dadok/gaerval/domain/user/service/DefaultUserService.java
  src/main/java/com/dadok/gaerval/domain/user/service/UserService.java
  src/main/java/com/dadok/gaerval/domain/user/vo/Nickname.java
  src/main/java/com/dadok/gaerval/global/error/exception/DuplicateException.java
  src/test/java/com/dadok/gaerval/domain/user/api/UserControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/user/service/DefaultUserServiceSliceTest.java
Labels: :sparkles: feat, :white_check_mark: test

#67 모임 목록 조회 기능 구현
  Dockerfile
  docker-compose.yml
  src/main/java/com/dadok/gaerval/domain/book/dto/response/SuggestionsBookFindResponses.java
  src/main/java/com/dadok/gaerval/domain/book_group/api/BookGroupController.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/request/BookGroupSearchRequest.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/response/BookGroupResponse.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/response/BookGroupResponses.java
  src/main/java/com/dadok/gaerval/domain/book_group/entity/BookGroup.java
  src/main/java/com/dadok/gaerval/domain/book_group/entity/GroupComment.java
  src/main/java/com/dadok/gaerval/domain/book_group/entity/GroupMember.java
  src/main/java/com/dadok/gaerval/domain/book_group/exception/InvalidCommentException.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupRepository.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupport.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/BookGroupService.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/BookInShelfResponses.java
  src/main/java/com/dadok/gaerval/global/error/ErrorCode.java
  src/main/java/com/dadok/gaerval/global/error/exception/InvalidArgumentException.java
  src/main/java/com/dadok/gaerval/global/util/CommonValidator.java
  src/main/java/com/dadok/gaerval/global/util/QueryDslUtil.java
  src/test/java/com/dadok/gaerval/domain/book/api/BookControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/DefaultBookServiceSliceTest.java
  src/test/java/com/dadok/gaerval/domain/bookGroup/entity/BookGroupTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupControllerTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/entity/BookGroupTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/entity/GroupCommentTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/entity/GroupMemberTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupportImplTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupServiceSliceTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfControllerSliceTest.java
  src/test/java/com/dadok/gaerval/testutil/BookGroupObjectProvider.java
  src/test/java/com/dadok/gaerval/testutil/GroupCommentObjectProvider.java
  src/test/java/com/dadok/gaerval/testutil/UserObjectProvider.java
Labels: :sparkles: feat, :recycle: refactor, :white_check_mark: test, :bug: fix

#68 test data sql (user, bookshelf)
  src/main/java/com/dadok/gaerval/domain/book/service/BookService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/entity/Bookshelf.java
  src/main/resources/sql/bookshelf_data.sql
  src/main/resources/sql/users_data.sql
  src/test/java/com/dadok/gaerval/domain/bookshelf/entity/BookshelfTest.java
Labels: 백엔드, :white_check_mark: test, :memo: chore

#70 book sample data 추가
  src/main/java/com/dadok/gaerval/domain/book/entity/Book.java
  src/main/resources/sql/books.sql
Labels: 백엔드, :sparkles: feat, :memo: chore

#69 refactor : anonymous도 허용할 수 있도록 시큐리티 로직 수정
  lombok.config
  src/main/java/com/dadok/gaerval/global/config/security/SecurityConfig.java
  src/main/java/com/dadok/gaerval/global/config/security/filter/ExceptionHandlingFilter.java
  src/main/java/com/dadok/gaerval/global/config/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/dadok/gaerval/global/config/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/dadok/gaerval/global/config/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/dadok/gaerval/global/config/security/jwt/JwtService.java
  src/main/java/com/dadok/gaerval/global/config/web/WebConfig.java
  src/main/java/com/dadok/gaerval/global/error/handler/GlobalExceptionHandler.java
  src/main/resources/application.yml
  src/main/resources/static/favicon.ico
Labels: :recycle: refactor

#71 bookgroup create api 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/book_group/api/BookGroupController.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/request/BookGroupCreateRequest.java
  src/main/java/com/dadok/gaerval/domain/book_group/entity/BookGroup.java
  src/main/java/com/dadok/gaerval/domain/book_group/entity/GroupMember.java
  src/main/java/com/dadok/gaerval/domain/book_group/exception/AlreadyContainBookGroupException.java
  src/main/java/com/dadok/gaerval/domain/book_group/exception/ExceedMaximumNumberOfMemberException.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/BookGroupService.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupService.java
  src/main/java/com/dadok/gaerval/global/error/ErrorCode.java
  src/main/java/com/dadok/gaerval/global/error/handler/GlobalExceptionHandler.java
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupControllerTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/entity/BookGroupTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupportImplTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupServiceSliceTest.java
Labels: 백엔드, :sparkles: feat, :white_check_mark: test

#72 find my groups 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/book_group/api/BookGroupController.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/response/BookGroupResponse.java
  src/main/java/com/dadok/gaerval/domain/book_group/entity/BookGroup.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupport.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/BookGroupService.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupService.java
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupControllerTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupportImplTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupServiceSliceTest.java
Labels: 백엔드, :sparkles: feat, :white_check_mark: test

#73 모임 상세 조회 구현
  build.gradle
  lombok.config
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/book_group/api/BookGroupController.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/response/BookGroupDetailResponse.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/response/BookGroupResponse.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupport.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/GroupMemberRepository.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/BookGroupService.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/entity/BookshelfItem.java
  src/main/java/com/dadok/gaerval/domain/user/entity/UserAuthority.java
  src/main/java/com/dadok/gaerval/global/config/web/WebConfig.java
  src/main/java/com/dadok/gaerval/global/util/QueryDslUtil.java
  src/main/resources/static/docs/common/jobGroup.html
  src/main/resources/static/docs/common/sortDirection.html
  src/main/resources/static/docs/index.html
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupportImplTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupServiceSliceTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/entity/BookshelfItemTest.java
  src/test/java/com/dadok/gaerval/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/dadok/gaerval/testutil/BookGroupObjectProvider.java
  src/test/java/com/dadok/gaerval/testutil/BookObjectProvider.java
  src/test/java/com/dadok/gaerval/testutil/UserObjectProvider.java
Labels: :sparkles: feat, :recycle: refactor, :white_check_mark: test, :memo: chore

#66 [#58] 책 코멘트 엔티티 구현
  src/main/java/com/dadok/gaerval/domain/book/converter/BookMapper.java
  src/main/java/com/dadok/gaerval/domain/book/entity/BookComment.java
  src/main/java/com/dadok/gaerval/domain/book/exception/InvalidBookDataException.java
  src/main/java/com/dadok/gaerval/global/config/externalapi/ExternalBookApiOperations.java
  src/test/java/com/dadok/gaerval/domain/book/entity/BookCommentTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/DefaultBookServiceTest.java
Labels: 백엔드, :sparkles: feat, :white_check_mark: test

#75 refactor : 직군, 직업 응답방식 변경
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/job/dto/response/JobGroupResponse.java
  src/main/java/com/dadok/gaerval/domain/job/dto/response/JobResponse.java
  src/main/java/com/dadok/gaerval/domain/job/dto/response/JobResponses.java
  src/main/java/com/dadok/gaerval/domain/job/service/DefaultJobService.java
  src/main/resources/static/docs/common/authProvider.html
  src/main/resources/static/docs/common/bookshelfItemType.html
  src/main/resources/static/docs/common/gender.html
  src/main/resources/static/docs/common/jobGroup.html
  src/main/resources/static/docs/common/jobName.html
  src/main/resources/static/docs/common/sortDirection.html
  src/main/resources/static/docs/index.html
  src/test/java/com/dadok/gaerval/domain/job/api/JobControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/job/service/DefaultJobServiceTest.java
  src/test/java/com/dadok/gaerval/testutil/JobObjectProvider.java
  src/test/resources/sql/jobs_data.sql
Labels: :recycle: refactor

#74 feat : bookgroup 참여제한 질문,비밀번호 필드 추가;
  src/main/java/com/dadok/gaerval/domain/book_group/dto/request/BookGroupCreateRequest.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/response/BookGroupDetailResponse.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/response/BookGroupResponse.java
  src/main/java/com/dadok/gaerval/domain/book_group/entity/BookGroup.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupService.java
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/entity/BookGroupTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupportImplTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupServiceSliceTest.java
  src/test/java/com/dadok/gaerval/testutil/BookGroupObjectProvider.java
Labels: 백엔드, :sparkles: feat, :recycle: refactor, :white_check_mark: test

#76 refector : findBookSummary dto projection으로 변경
  src/main/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfController.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/BookShelfSummaryResponse.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/PopularBookshelvesOfJobResponses.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/SummaryBookshelfResponse.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfRepository.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfSupport.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/BookshelfService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfService.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfRepositoryTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfServiceSliceTest.java
Labels: 백엔드, :recycle: refactor

#80 미사용자를 위한 책장 추천리스트 조회 api 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/book/dto/response/BookResponse.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfController.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/SuggestionBookshelvesResponses.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfSupport.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/BookshelfService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfService.java
  src/test/java/com/dadok/gaerval/domain/book/api/BookControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfRepositoryTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfServiceSliceTest.java
Labels: 백엔드, :sparkles: feat, :recycle: refactor, :white_check_mark: test

#77 config : logback 설정 추가
  src/main/resources/logback-spring.xml
Labels: 백엔드, :wrench: config

#82 bookGroup delete 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/book_group/api/BookGroupController.java
  src/main/java/com/dadok/gaerval/domain/book_group/entity/BookGroup.java
  src/main/java/com/dadok/gaerval/domain/book_group/exception/BookGroupOwnerNotMatchedException.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupRepository.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/BookGroupService.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfSupportImpl.java
  src/main/java/com/dadok/gaerval/global/error/ErrorCode.java
  src/main/java/com/dadok/gaerval/global/error/handler/GlobalExceptionHandler.java
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupServiceSliceTest.java
Labels: 백엔드, :sparkles: feat

#83 feat : 모임 가입 기능 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/book_group/api/BookGroupController.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/request/BookGroupJoinRequest.java
  src/main/java/com/dadok/gaerval/domain/book_group/entity/BookGroup.java
  src/main/java/com/dadok/gaerval/domain/book_group/entity/GroupMember.java
  src/main/java/com/dadok/gaerval/domain/book_group/exception/AlreadyContainBookGroupException.java
  src/main/java/com/dadok/gaerval/domain/book_group/exception/ExceedLimitMemberException.java
  src/main/java/com/dadok/gaerval/domain/book_group/exception/ExceedMaximumNumberOfMemberException.java
  src/main/java/com/dadok/gaerval/domain/book_group/exception/NotMatchedPasswordException.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupRepository.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/GroupMemberRepository.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/BookGroupService.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupService.java
  src/main/java/com/dadok/gaerval/global/error/ErrorCode.java
  src/main/java/com/dadok/gaerval/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/dadok/gaerval/global/util/CommonValidator.java
  src/main/java/com/dadok/gaerval/global/util/RegexHelper.java
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/entity/BookGroupTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupportImplTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupServiceSliceTest.java
  src/test/java/com/dadok/gaerval/testutil/BookGroupObjectProvider.java
Labels: :sparkles: feat, :recycle: refactor

#84 feat : 모임 댓글 api 개발
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/book_group/api/BookGroupCommentController.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/request/BookGroupCommentCreateRequest.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/request/BookGroupCommentSearchRequest.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/response/BookGroupCommentResponse.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/response/BookGroupCommentResponses.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupCommentRepository.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupCommentSupport.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupCommentSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/BookGroupCommentService.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/BookGroupService.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupCommentService.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupService.java
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupCommentControllerTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/repository/BookGroupCommentSupportImplTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupCommentServiceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupServiceSliceTest.java
  src/test/java/com/dadok/gaerval/testutil/BookGroupCommentObjectProvider.java
Labels: 백엔드, :sparkles: feat

#85 refactor : 그룹 가입시 마감 날짜가 지나면 가입 못하도록 수정
  src/main/java/com/dadok/gaerval/domain/book_group/entity/BookGroup.java
  src/main/java/com/dadok/gaerval/domain/book_group/exception/ExpiredJoinGroupPeriodException.java
  src/main/java/com/dadok/gaerval/global/error/ErrorCode.java
  src/main/java/com/dadok/gaerval/global/error/handler/GlobalExceptionHandler.java
  src/test/java/com/dadok/gaerval/domain/book_group/entity/BookGroupTest.java
Labels: :recycle: refactor

#86 feat : 도서 추가 api 개발
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/book/api/BookController.java
  src/main/java/com/dadok/gaerval/domain/book/dto/response/BookIdResponse.java
  src/main/java/com/dadok/gaerval/domain/book/service/BookService.java
  src/main/java/com/dadok/gaerval/domain/book/service/DefaultBookService.java
  src/test/java/com/dadok/gaerval/domain/book/api/BookControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/DefaultBookServiceTest.java
Labels: 백엔드, :sparkles: feat

#87 모임 생성, bookshelfItem 생성시 bookcreate 제외
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/book/service/BookService.java
  src/main/java/com/dadok/gaerval/domain/book/service/DefaultBookService.java
  src/main/java/com/dadok/gaerval/domain/book_group/api/BookGroupController.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/request/BookGroupCreateRequest.java
  src/main/java/com/dadok/gaerval/domain/book_group/exception/BookGroupOwnerNotMatchedException.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfController.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/request/BookshelfItemCreateRequest.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/BookshelfService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfService.java
  src/test/java/com/dadok/gaerval/domain/book/service/DefaultBookServiceSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/DefaultBookServiceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupServiceSliceTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfServiceSliceTest.java
Labels: 백엔드, :recycle: refactor, :white_check_mark: test

#88 refact : 반복작업 함수 호출로 변경
  src/main/java/com/dadok/gaerval/domain/book/converter/BookMapper.java
  src/main/java/com/dadok/gaerval/domain/book/entity/Book.java
  src/main/java/com/dadok/gaerval/domain/book/service/DefaultBookService.java
Labels: 백엔드, :recycle: refactor

#89 통합 테스트
  .gitignore
  src/main/java/com/dadok/gaerval/domain/user/service/DefaultUserService.java
  src/main/resources/sql/authority_data.sql
  src/main/resources/sql/authority_init.sql
  src/main/resources/sql/job_data.sql
  src/main/resources/sql/jobs_data.sql
  src/main/resources/sql/schema.sql
  src/test/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupportImplTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfRepositoryTest.java
  src/test/java/com/dadok/gaerval/domain/job/service/JobServiceTest.java
  src/test/java/com/dadok/gaerval/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/dadok/gaerval/domain/user/service/UserServiceTest.java
  src/test/java/com/dadok/gaerval/integration_util/ServiceIntegration.java
  src/test/java/com/dadok/gaerval/testutil/UserObjectProvider.java
Labels: :white_check_mark: test

#92 [refector] 프론트 요청 응답값 변경
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/book_group/api/BookGroupController.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/response/BookGroupIdResponse.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/response/BookGroupResponse.java
  src/main/java/com/dadok/gaerval/domain/book_group/entity/BookGroup.java
  src/main/java/com/dadok/gaerval/domain/book_group/exception/CannotDeleteMemberExistException.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/DetailBookshelfResponse.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/BookshelfService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfService.java
  src/main/java/com/dadok/gaerval/global/error/ErrorCode.java
  src/main/java/com/dadok/gaerval/global/error/handler/GlobalExceptionHandler.java
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupServiceSliceTest.java
  src/test/java/com/dadok/gaerval/testutil/BookGroupObjectProvider.java
Labels: 백엔드, :white_check_mark: test, :memo: chore, :bug: fix

#91 [#90] feat : 모임 댓글 본인 여부, 닉네임 추가
  src/main/java/com/dadok/gaerval/domain/book_group/dto/response/BookGroupCommentResponse.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupCommentSupportImpl.java
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupCommentControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupCommentServiceTest.java
  src/test/java/com/dadok/gaerval/testutil/BookGroupCommentObjectProvider.java
Labels: 백엔드, :sparkles: feat

#94 refactor : 모임 리스트 조회 쿼리 버그 수정
  src/main/java/com/dadok/gaerval/domain/book_group/entity/GroupMember.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupportImpl.java
Labels: :recycle: refactor, :bug: fix

#96 Feature/fix bookgroup - 유저 책장 업데이트시, 책장이 없다면 책장 생성
  src/main/java/com/dadok/gaerval/domain/bookshelf/entity/Bookshelf.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/BookshelfService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfService.java
  src/main/java/com/dadok/gaerval/domain/user/service/DefaultUserService.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfServiceSliceTest.java
  src/test/java/com/dadok/gaerval/domain/user/service/DefaultUserServiceSliceTest.java
  src/test/java/com/dadok/gaerval/domain/user/service/UserServiceTest.java
  src/test/java/com/dadok/gaerval/integration_util/ServiceIntegration.java
Labels: :recycle: refactor, :bug: fix

#97 Feature/book comment api
  build.gradle
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/index.html
  src/main/java/com/dadok/gaerval/domain/book/api/BookCommentController.java
  src/main/java/com/dadok/gaerval/domain/book/api/BookController.java
  src/main/java/com/dadok/gaerval/domain/book/dto/request/BookCommentCreateRequest.java
  src/main/java/com/dadok/gaerval/domain/book/dto/request/BookCommentSearchRequest.java
  src/main/java/com/dadok/gaerval/domain/book/dto/request/BookCommentUpdateRequest.java
  src/main/java/com/dadok/gaerval/domain/book/dto/response/BookCommentIdResponse.java
  src/main/java/com/dadok/gaerval/domain/book/dto/response/BookCommentResponse.java
  src/main/java/com/dadok/gaerval/domain/book/dto/response/BookCommentResponses.java
  src/main/java/com/dadok/gaerval/domain/book/entity/Book.java
  src/main/java/com/dadok/gaerval/domain/book/entity/BookComment.java
  src/main/java/com/dadok/gaerval/domain/book/exception/AlreadyContainBookCommentException.java
  src/main/java/com/dadok/gaerval/domain/book/repository/BookCommentRepository.java
  src/main/java/com/dadok/gaerval/domain/book/repository/BookCommentSupport.java
  src/main/java/com/dadok/gaerval/domain/book/repository/BookCommentSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/book/service/BookCommentService.java
  src/main/java/com/dadok/gaerval/domain/book/service/DefaultBookCommentService.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupCommentRepository.java
  src/main/java/com/dadok/gaerval/global/error/ErrorCode.java
  src/main/resources/logback-spring.xml
  src/main/resources/sql/schema.sql
  src/main/resources/static/docs/common/authProvider.html
  src/main/resources/static/docs/common/bookshelfItemType.html
  src/main/resources/static/docs/common/gender.html
  src/main/resources/static/docs/common/jobGroup.html
  src/main/resources/static/docs/common/jobName.html
  src/main/resources/static/docs/common/sortDirection.html
  src/main/resources/static/docs/index.html
  src/test/java/com/dadok/gaerval/domain/book/api/BookCommentControllerTest.java
  src/test/java/com/dadok/gaerval/domain/book/api/BookControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book/repository/BookCommentSupportImplTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/DefaultBookCommentServiceTest.java
  src/test/java/com/dadok/gaerval/testutil/BookCommentObjectProvider.java
Labels: 백엔드, :sparkles: feat

#100 책 상세 노출용 책을 꽂은 유저 정보 조회 api 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/book/api/BookController.java
  src/main/java/com/dadok/gaerval/domain/book/dto/response/UserByBookResponse.java
  src/main/java/com/dadok/gaerval/domain/book/dto/response/UserByBookResponses.java
  src/main/java/com/dadok/gaerval/domain/book/service/BookService.java
  src/main/java/com/dadok/gaerval/domain/book/service/DefaultBookService.java
  src/main/java/com/dadok/gaerval/domain/book_group/api/BookGroupController.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/request/BookGroupCreateRequest.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/request/BookGroupUpdateRequest.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/response/BookGroupDetailResponse.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/response/BookGroupResponse.java
  src/main/java/com/dadok/gaerval/domain/book_group/entity/BookGroup.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/BookShelfSummaryResponse.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookShelfItemSupport.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookShelfItemSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfService.java
  src/test/java/com/dadok/gaerval/domain/book/api/BookControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/DefaultBookServiceSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/repository/BookShelfItemSupportImplTest.java
Labels: 백엔드, :sparkles: feat, :white_check_mark: test

#102 refactor : 책장 책 조회 버그 수정
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookShelfItemSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfService.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/repository/BookShelfItemSupportImplTest.java
Labels: :recycle: refactor

#103 fix : 책장 꽂을 때 exist 확인
  src/main/java/com/dadok/gaerval/domain/bookshelf/entity/Bookshelf.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfService.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfServiceSliceTest.java
Labels: 백엔드, :white_check_mark: test, :bug: fix

#104 fix : 모임 리스트 출력 버그 픽스
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/entity/Bookshelf.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/entity/BookshelfItem.java
  src/main/java/com/dadok/gaerval/global/util/QueryDslUtil.java
  src/test/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupportImplTest.java
Labels: 백엔드, :bug: fix

#105 Feature/book comment delete api
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/book/api/BookCommentController.java
  src/main/java/com/dadok/gaerval/domain/book/dto/request/BookCommentDeleteRequest.java
  src/main/java/com/dadok/gaerval/domain/book/service/BookCommentService.java
  src/main/java/com/dadok/gaerval/domain/book/service/DefaultBookCommentService.java
  src/main/java/com/dadok/gaerval/global/error/handler/GlobalExceptionHandler.java
  src/test/java/com/dadok/gaerval/domain/book/api/BookCommentControllerTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/DefaultBookCommentServiceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupCommentControllerSliceTest.java
Labels: 백엔드, :sparkles: feat

#109 fix : 모임 댓글 수정, 삭제 버그 수정
  src/main/java/com/dadok/gaerval/domain/book_group/api/BookGroupCommentController.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/request/BookGroupCommentUpdateRequest.java
  src/main/java/com/dadok/gaerval/domain/book_group/entity/GroupComment.java
  src/main/java/com/dadok/gaerval/domain/book_group/exception/NotMatchedCommentAuthorException.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/BookGroupCommentService.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupCommentService.java
  src/main/java/com/dadok/gaerval/global/error/ErrorCode.java
  src/main/resources/sql/clean_up.sql
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupCommentControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/BookGroupCommentServiceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupCommentServiceSliceTest.java
  src/test/java/com/dadok/gaerval/integration_util/ServiceIntegration.java
Labels: :recycle: refactor, :bug: fix

#112 [#106 ] bookgroup comment 쿼리 버그 수정
  src/main/java/com/dadok/gaerval/domain/book/dto/response/BookCommentResponses.java
  src/main/java/com/dadok/gaerval/domain/book/repository/BookCommentSupport.java
  src/main/java/com/dadok/gaerval/domain/book/repository/BookCommentSupportImpl.java
  src/test/java/com/dadok/gaerval/domain/book/api/BookCommentControllerTest.java
  src/test/java/com/dadok/gaerval/domain/book/repository/BookCommentSupportImplTest.java
Labels: :white_check_mark: test, :bug: fix

#113 [# 111] By job Group path param 영어(enum값)로 통일
  src/main/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfController.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/SuggestionBookshelvesByJobGroupResponses.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/BookshelfService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfService.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfServiceSliceTest.java
Labels: :recycle: refactor, :memo: chore

#114 [#110 ] join 시 비밀번호 확인 버그 수정
  src/main/java/com/dadok/gaerval/domain/book_group/dto/request/BookGroupJoinRequest.java
  src/main/java/com/dadok/gaerval/domain/book_group/entity/BookGroup.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/SuggestionBookshelvesByJobGroupResponses.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfService.java
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/entity/BookGroupTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupServiceTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfControllerSliceTest.java
Labels: :recycle: refactor, :bug: fix

#115 book group 제한없음 정상 생성 버그 수정
  src/main/java/com/dadok/gaerval/domain/book_group/dto/request/BookGroupCreateRequest.java
  src/main/java/com/dadok/gaerval/domain/book_group/entity/BookGroup.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/BookShelfSummaryResponse.java
  src/main/java/com/dadok/gaerval/global/util/RegexHelper.java
  src/test/java/com/dadok/gaerval/domain/book_group/entity/BookGroupTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/BookGroupCommentServiceSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/BookGroupServiceSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/BookGroupServiceTest.java
Labels: 백엔드, :white_check_mark: test, :bug: fix

#118 refactor : 모임 댓글 리스트 조회 모임 공개여부 필드 포함하도록 수정
  src/main/java/com/dadok/gaerval/domain/book_group/dto/response/BookGroupCommentResponses.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupCommentSupportImpl.java
  src/main/resources/static/docs/index.html
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupCommentControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/BookGroupCommentServiceSliceTest.java
Labels: :recycle: refactor

#121 [#117 ]익명사용자 접근을 위한 empty user 구현
  src/main/java/com/dadok/gaerval/domain/book/api/BookCommentController.java
  src/main/java/com/dadok/gaerval/domain/book/api/BookController.java
  src/main/java/com/dadok/gaerval/domain/book/repository/BookCommentSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/book_group/api/BookGroupCommentController.java
  src/main/java/com/dadok/gaerval/domain/book_group/api/BookGroupController.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/response/BookGroupCommentResponses.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupCommentSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfController.java
  src/main/java/com/dadok/gaerval/global/config/security/CurrentUserPrincipal.java
  src/main/java/com/dadok/gaerval/global/config/security/EmptyUserPrincipal.java
  src/main/java/com/dadok/gaerval/global/config/security/UserPrincipal.java
  src/main/java/com/dadok/gaerval/global/util/QueryDslUtil.java
  src/main/resources/static/docs/common/authProvider.html
  src/main/resources/static/docs/common/bookshelfItemType.html
  src/main/resources/static/docs/common/errorCode.html
  src/main/resources/static/docs/common/gender.html
  src/main/resources/static/docs/common/jobGroup.html
  src/main/resources/static/docs/common/jobName.html
  src/main/resources/static/docs/common/sortDirection.html
  src/test/java/com/dadok/gaerval/domain/book/api/BookCommentControllerTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/BookCommentServiceSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/BookCommentServiceTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/BookServiceSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/BookServiceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupCommentControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/BookGroupCommentServiceSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/BookGroupCommentServiceTest.java
  src/test/java/com/dadok/gaerval/integration_util/IntegrationTest.java
  src/test/resources/sql/book_comment/book_comment_data.sql
Labels: :sparkles: feat, :recycle: refactor, :white_check_mark: test, :memo: chore, :bug: fix

#124 fix : bookGruop comments 응답 변경
  src/main/java/com/dadok/gaerval/domain/book/api/BookCommentController.java
  src/main/java/com/dadok/gaerval/domain/book/dto/request/BookCommentDeleteRequest.java
  src/main/java/com/dadok/gaerval/domain/book/repository/BookCommentSupport.java
  src/main/java/com/dadok/gaerval/domain/book/repository/BookCommentSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/book/service/BookCommentService.java
  src/main/java/com/dadok/gaerval/domain/book/service/DefaultBookCommentService.java
  src/main/java/com/dadok/gaerval/domain/book_group/api/BookGroupCommentController.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/request/BookGroupCommentDeleteRequest.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/response/BookGroupCommentResponses.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupCommentSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/BookGroupCommentService.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupCommentService.java
  src/main/java/com/dadok/gaerval/global/error/ErrorCode.java
  src/test/java/com/dadok/gaerval/domain/book/api/BookCommentControllerTest.java
  src/test/java/com/dadok/gaerval/domain/book/repository/BookCommentSupportImplTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/BookCommentServiceSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupCommentControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/BookGroupCommentServiceSliceTest.java
Labels: :bug: fix

#127 refact : http 로깅 AOP 적용
  src/main/java/com/dadok/gaerval/domain/book/api/BookCommentController.java
  src/main/java/com/dadok/gaerval/domain/book/api/BookController.java
  src/main/java/com/dadok/gaerval/global/common/logging/LogHttpRequests.java
  src/main/java/com/dadok/gaerval/global/common/logging/LoggingAspect.java
Labels: 백엔드, :sparkles: feat

#135 bookgroup 탈퇴 api 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/book_group/api/BookGroupController.java
  src/main/java/com/dadok/gaerval/domain/book_group/entity/BookGroup.java
  src/main/java/com/dadok/gaerval/domain/book_group/exception/CannotLeaveGroupOwnerException.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/GroupMemberRepository.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/BookGroupService.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupService.java
  src/main/java/com/dadok/gaerval/global/error/ErrorCode.java
  src/main/resources/application.yml
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/BookGroupServiceSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/service/BookGroupServiceTest.java
Labels: :sparkles: feat, :white_check_mark: test

#133 Refactor/search book api
  src/main/java/com/dadok/gaerval/domain/book/api/BookController.java
  src/main/java/com/dadok/gaerval/domain/book/dto/request/BookSearchRequest.java
  src/main/java/com/dadok/gaerval/domain/book/dto/response/BookResponses.java
  src/main/java/com/dadok/gaerval/domain/book/exception/BookApiNotAvailableException.java
  src/main/java/com/dadok/gaerval/domain/book/service/BookDataProcessor.java
  src/main/java/com/dadok/gaerval/domain/book/service/BookService.java
  src/main/java/com/dadok/gaerval/domain/book/service/DefaultBookService.java
  src/main/java/com/dadok/gaerval/global/config/externalapi/ExternalApiError.java
  src/main/java/com/dadok/gaerval/global/config/externalapi/ExternalBookApiOperations.java
  src/main/java/com/dadok/gaerval/global/config/externalapi/WebClientBookApiOperations.java
  src/main/java/com/dadok/gaerval/global/error/ErrorCode.java
  src/main/java/com/dadok/gaerval/global/error/handler/GlobalExceptionHandler.java
  src/test/java/com/dadok/gaerval/domain/book/api/BookControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/BookServiceTest.java
  src/test/java/com/dadok/gaerval/testutil/BookObjectProvider.java
Labels: 백엔드, :sparkles: feat, :recycle: refactor

#138 [#137 ]책장속 책 pagenation cursorId 변경
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/request/BooksInBookShelfFindRequest.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/BookInShelfResponses.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookShelfItemSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfService.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfControllerSliceTest.java
Labels: :bug: fix

#140 [#139] 도서 리뷰 저장 시 북마크 여부 검증하는 로직 추가
  src/main/java/com/dadok/gaerval/domain/book/api/BookCommentController.java
  src/main/java/com/dadok/gaerval/domain/book/exception/NotMarkedBookException.java
  src/main/java/com/dadok/gaerval/domain/book/service/DefaultBookCommentService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/BookshelfService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfService.java
  src/main/java/com/dadok/gaerval/global/error/ErrorCode.java
  src/main/java/com/dadok/gaerval/global/error/handler/GlobalExceptionHandler.java
  src/test/java/com/dadok/gaerval/domain/book/service/BookCommentServiceSliceTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfServiceSliceTest.java
Labels: 백엔드, :sparkles: feat
