Repository prgrms-web-devcourse/Team-Gaerval-Dadok-BE, pull requests merged in 2023-02, with the labels that each got.

#15 [#14] fix : .gradle 폴더 gitignore 리스트 추가
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
Labels: 백엔드, :wrench: config, :memo: chore

#23 [#22] 서비스 인터페이스 정의
  src/main/java/com/dadok/gaerval/domain/book/service/BookService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/BookshelfService.java
  src/main/java/com/dadok/gaerval/domain/job/service/JobService.java
Labels: 백엔드, :sparkles: feat, :wrench: config

#24 [#6] Book 엔티티 구현
  src/main/java/com/dadok/gaerval/domain/book/entity/Book.java
  src/test/java/com/dadok/gaerval/domain/book/entity/BookTest.java
  src/test/java/com/dadok/gaerval/testutil/BookObjectProvider.java
Labels: 백엔드, :sparkles: feat

#25 chore : id 파라미터 제외
  src/test/java/com/dadok/gaerval/domain/book/entity/BookTest.java
Labels: 백엔드, :memo: chore

#27 [#5 ] 카카오 로그인 구현 및 Jwt 인증 구현
  src/main/java/com/dadok/gaerval/global/config/security/filter/JwtAuthenticationFilter.java
Labels: :recycle: refactor

#26 [#7 ] bookshelf 엔티티 구현 및 테스트
  .github/pull_request_template.md
  .gradle/7.6/checksums/checksums.lock
  .gradle/7.6/dependencies-accessors/dependencies-accessors.lock
  .gradle/7.6/dependencies-accessors/gc.properties
  .gradle/7.6/executionHistory/executionHistory.bin
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileChanges/last-build.bin
  .gradle/7.6/fileHashes/fileHashes.bin
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/7.6/fileHashes/resourceHashesCache.bin
  .gradle/7.6/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .gradle/vcs-1/gc.properties
  src/main/java/com/dadok/gaerval/domain/bookshelf/entity/Bookshelf.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/entity/BookshelfItem.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/entity/BookshelfItemType.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/entity/BookshelfItemTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/entity/BookshelfTest.java
Labels: 백엔드, :sparkles: feat, :white_check_mark: test

#29 [#10, #11] 책장 추가, 제거 service 레이어 구현
  src/main/java/com/dadok/gaerval/domain/book/dto/request/BookCreateRequest.java
  src/main/java/com/dadok/gaerval/domain/book/service/BookService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/BookshelfSummaryResponse.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/DetailBookshelfResponse.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/PopularBookshelfOfJobResponses.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/entity/Bookshelf.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/entity/BookshelfItem.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/exception/AlreadyContainBookshelfItemException.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/exception/BookshelfUserNotMatchedException.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfItemRepository.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfRepository.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/BookshelfService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfService.java
  src/main/java/com/dadok/gaerval/global/error/ErrorCode.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/entity/BookshelfItemTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/entity/BookshelfTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfItemRepositoryTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfServiceSliceTest.java
Labels: :sparkles: feat, :white_check_mark: test

#33 [#8 ][#10 ][#11 ] bookshelf controller 구현 및 slice test 구현
  src/docs/asciidoc/common/bookshelfItemType.adoc
  src/main/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfController.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/BookshelfSummaryResponse.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/PopularBookshelfOfJobResponses.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/PopularBookshelvesOfJobResponses.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/SummaryBookshelfResponse.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/entity/Bookshelf.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/entity/BookshelfItem.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfRepository.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/BookshelfService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfService.java
  src/main/java/com/dadok/gaerval/domain/job/entity/JobGroup.java
  src/main/java/com/dadok/gaerval/global/error/handler/GlobalExceptionHandler.java
  src/test/java/com/dadok/gaerval/controller/EnumDocsControllerTest.java
  src/test/java/com/dadok/gaerval/controller/document/EnumDocs.java
  src/test/java/com/dadok/gaerval/controller/document/EnumDocsController.java
  src/test/java/com/dadok/gaerval/controller/document/utils/DocumentLinkGenerator.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfControllerIntegrationTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfItemRepositoryTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfRepositoryTest.java
  src/test/java/com/dadok/gaerval/domain/job/api/JobControllerSliceTest.java
Labels: 백엔드, :sparkles: feat, :white_check_mark: test
