Repository prgrms-web-devcourse/Team-Gaerval-Dadok-BE, pull requests merged in 2023-04, with the labels that each got.

#147 [#146] 도서 검색 페이지 사이즈 값 반영
  src/main/java/com/dadok/gaerval/domain/book/dto/request/BookSearchRequest.java
  src/main/java/com/dadok/gaerval/domain/book/dto/response/BookResponses.java
  src/main/java/com/dadok/gaerval/domain/book/service/DefaultBookService.java
  src/main/java/com/dadok/gaerval/global/config/externalapi/WebClientBookApiOperations.java
  src/test/java/com/dadok/gaerval/domain/book/api/BookControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/BookServiceTest.java
  src/test/java/com/dadok/gaerval/testutil/BookObjectProvider.java
Labels: 백엔드, :sparkles: feat, :bug: fix

#149 [#148] config : 로깅 전략 수정
  src/main/resources/logback-spring.xml
Labels: :wrench: config

#152 [#151]fix : enum 참조 방식 변경
  src/main/java/com/dadok/gaerval/domain/book/exception/AlreadyContainBookCommentException.java
  src/main/java/com/dadok/gaerval/domain/book/exception/BookApiNotAvailableException.java
  src/main/java/com/dadok/gaerval/domain/book/exception/InvalidBookDataException.java
  src/main/java/com/dadok/gaerval/domain/book/exception/NotMarkedBookException.java
  src/main/java/com/dadok/gaerval/domain/book/repository/BookSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/book/service/DefaultBookCommentService.java
  src/main/java/com/dadok/gaerval/domain/book/service/DefaultBookService.java
Labels: :bug: fix

#154 feat : 모임 검색 like 기반 구현
  src/docs/asciidoc/common/groupSearchOption.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/book_group/api/BookGroupController.java
  src/main/java/com/dadok/gaerval/domain/book_group/dto/request/BookGroupQueryRequest.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupport.java
  src/main/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/BookGroupService.java
  src/main/java/com/dadok/gaerval/domain/book_group/service/DefaultBookGroupService.java
  src/main/resources/static/docs/common/authProvider.html
  src/main/resources/static/docs/common/bookshelfItemType.html
  src/main/resources/static/docs/common/errorCode.html
  src/main/resources/static/docs/common/gender.html
  src/main/resources/static/docs/common/jobGroup.html
  src/main/resources/static/docs/common/jobName.html
  src/main/resources/static/docs/common/sortDirection.html
  src/main/resources/static/docs/index.html
  src/test/java/com/dadok/gaerval/controller/EnumDocs.java
  src/test/java/com/dadok/gaerval/controller/EnumDocsController.java
  src/test/java/com/dadok/gaerval/controller/EnumDocsControllerTest.java
  src/test/java/com/dadok/gaerval/controller/document/utils/DocumentLinkGenerator.java
  src/test/java/com/dadok/gaerval/domain/book_group/api/BookGroupControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book_group/repository/BookGroupSupportImplTest.java
Labels: :sparkles: feat

#160 [#145] 좋아요 추가, 삭제 api 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfLikeController.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/entity/Bookshelf.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/entity/BookshelfLike.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/exception/AlreadyExistsBookshelfLikeException.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfLikeRepository.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfLikeSupport.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfLikeSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/BookshelfLikeService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfLikeService.java
  src/main/java/com/dadok/gaerval/global/error/ErrorCode.java
  src/main/java/com/dadok/gaerval/global/error/handler/GlobalExceptionHandler.java
  src/main/resources/sql/schema.sql
  src/test/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfLikeControllerTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/entity/BookshelfLikeTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfLikeRepositoryTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfLikeServiceTest.java
Labels: 백엔드, :sparkles: feat, :white_check_mark: test

#163 feat: 유저명으로 유저 프로필 목록 조회 api 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/book/entity/BookRecentSearch.java
  src/main/java/com/dadok/gaerval/domain/user/api/UserController.java
  src/main/java/com/dadok/gaerval/domain/user/dto/response/UserProfileResponses.java
  src/main/java/com/dadok/gaerval/domain/user/repository/UserRepository.java
  src/main/java/com/dadok/gaerval/domain/user/repository/UserSupport.java
  src/main/java/com/dadok/gaerval/domain/user/repository/UserSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/user/service/DefaultUserService.java
  src/main/java/com/dadok/gaerval/domain/user/service/UserService.java
  src/main/resources/sql/clean_up.sql
  src/main/resources/sql/schema.sql
  src/test/java/com/dadok/gaerval/domain/user/api/UserControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/dadok/gaerval/testutil/JobObjectProvider.java
  src/test/resources/sql/user/users_and_job.sql
Labels: :sparkles: feat

#164 [#158 ]refact : 북마크에서 해제된 도서 리뷰를 수정할 수 있도록 변경
  src/main/java/com/dadok/gaerval/domain/book/service/DefaultBookCommentService.java
  src/test/java/com/dadok/gaerval/domain/book/service/BookCommentServiceSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/DefaultBookCommentServiceTest.java
Labels: :recycle: refactor
