Repository prgrms-web-devcourse/Team-Gaerval-Dadok-BE, pull requests merged in 2023-05, with the labels that each got.

#166 [#145 ] 책장 좋아요 개수 추가 & 내가 좋아요한 책장 list 조회
  src/docs/asciidoc/index.adoc
  src/main/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfController.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/request/LikedBookShelvesRequest.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/BookShelfDetailResponse.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/BookShelfSummaryResponse.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/dto/response/BookshelvesResponses.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfSupport.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/BookshelfService.java
  src/main/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfService.java
  src/main/java/com/dadok/gaerval/domain/user/dto/response/UserDetailResponse.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/api/BookshelfLikeControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/repository/BookshelfRepositoryTest.java
  src/test/java/com/dadok/gaerval/domain/bookshelf/service/DefaultBookshelfServiceSliceTest.java
Labels: :sparkles: feat, :white_check_mark: test

#168 [#146]feat : 베스트셀러 조회 API 구현
  src/docs/asciidoc/common/bestSellerSearchRange.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/index.html
  src/main/java/com/dadok/gaerval/domain/book/api/BookController.java
  src/main/java/com/dadok/gaerval/domain/book/converter/BookMapper.java
  src/main/java/com/dadok/gaerval/domain/book/dto/request/BestSellerSearchRange.java
  src/main/java/com/dadok/gaerval/domain/book/dto/request/BestSellerSearchRequest.java
  src/main/java/com/dadok/gaerval/domain/book/dto/response/BestSellerBookResponse.java
  src/main/java/com/dadok/gaerval/domain/book/dto/response/BestSellerBookResponses.java
  src/main/java/com/dadok/gaerval/domain/book/dto/response/OriginalBookData.java
  src/main/java/com/dadok/gaerval/domain/book/service/BookDataProcessor.java
  src/main/java/com/dadok/gaerval/domain/book/service/BookService.java
  src/main/java/com/dadok/gaerval/domain/book/service/DefaultBookCommentService.java
  src/main/java/com/dadok/gaerval/domain/book/service/DefaultBookService.java
  src/main/java/com/dadok/gaerval/domain/book/service/SaveKeywordEventListener.java
  src/main/java/com/dadok/gaerval/global/config/externalapi/AladinWebClientConfig.java
  src/main/java/com/dadok/gaerval/global/config/externalapi/BookApiProvider.java
  src/main/java/com/dadok/gaerval/global/config/externalapi/ExternalBookApiOperations.java
  src/main/java/com/dadok/gaerval/global/config/externalapi/KakaoWebClientConfig.java
  src/main/java/com/dadok/gaerval/global/config/externalapi/VendorWebClient.java
  src/main/java/com/dadok/gaerval/global/config/externalapi/WebClientBookApiOperations.java
  src/main/java/com/dadok/gaerval/global/config/externalapi/WebClientProperties.java
  src/main/resources/application-api.yml
  src/test/java/com/dadok/gaerval/controller/EnumDocs.java
  src/test/java/com/dadok/gaerval/controller/EnumDocsController.java
  src/test/java/com/dadok/gaerval/controller/EnumDocsControllerTest.java
  src/test/java/com/dadok/gaerval/controller/document/utils/DocumentLinkGenerator.java
  src/test/java/com/dadok/gaerval/domain/book/api/BookControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/BookDataProcessTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/SaveKeywordEventListenerTest.java
  src/test/java/com/dadok/gaerval/testutil/BookObjectProvider.java
Labels: :sparkles: feat

#170 [#169] feat : 도서 검색 시 최근 키워드 저장 여부를 선택할 수 있도록 변경
  src/main/java/com/dadok/gaerval/domain/book/dto/request/BookSearchRequest.java
  src/main/java/com/dadok/gaerval/domain/book/dto/response/BookRecentSearchResponse.java
  src/main/java/com/dadok/gaerval/domain/book/repository/BookRecentSearchSupportImpl.java
  src/main/java/com/dadok/gaerval/domain/book/service/DefaultBookService.java
  src/test/java/com/dadok/gaerval/domain/book/api/BookControllerSliceTest.java
  src/test/java/com/dadok/gaerval/domain/book/repository/BookRecentSearchSupportImplTest.java
  src/test/java/com/dadok/gaerval/domain/book/service/BookServiceTest.java
Labels: 백엔드, :sparkles: feat
